export const GET_RESTAURANTS = "GET_RESTAURANTS"

export const FETCH_PLACES_GOOGLE = "FETCH_PLACES_GOOGLE"

export const STORE_CITY_STATE = "STORE_CITY_STATE"

export const PAGE_NUMBER = "PAGE_NUMBER"