export const GET_RESTAURANTS = "GET_RESTAURANTS";

export const FETCH_PLACES_GOOGLE = "FETCH_PLACES_GOOGLE";

export const STORE_CITY_STATE = "STORE_CITY_STATE";

export const PAGE_NUMBER = "PAGE_NUMBER";

export const GET_RESTAURANT_INFO = "GET_RESTAURANT_INFO";

export const SET_SHOW = "SET_SHOW";

export const ERR_SEARCH = "ERR_SEARCH";
